/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.gov.mf.jpk.jpksendapp;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import java.util.logging.LogRecord;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.text.DefaultCaret;
import pl.gov.mf.jpk.jpksendapp.Main.ReleaseMode;
import pl.gov.mf.jpk.jpksendapp.http.RestClient;

/**
 *
 * @author xmo
 */
public class WinApp extends JFrame
{
    public static final Logger LOGGER = Logger.getLogger(WinApp.class.getName());

    public static final String FILE_DOT_EXT_UPO = ".xml";
    public static final String FILE_DOT_EXT_TXT = ".txt";
    public static final String FILE_DOT_EXT_XADES = ".xades";
    
    public static final String JPK_SEND_MODE_TST = "Tryb testowy";
    public static final String JPK_SEND_MODE_PRD = "Tryb produkcyjny";
    
    private File upoFile = null;
    private File xadesFile = null;
    private RestClient restClient = null;
    private NoticeHandler noticeHandler = null;

    public WinApp()
    {
        initAppContext();
        
        initComponents();
        
        setLocation(300, 150);
        
        ((DefaultCaret) textArea.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        if (Main.APP_RELEASE_LEVEL == Main.ReleaseLevel.TST)
        {
            modeToggleButton.setEnabled(false);
        }
        
        this.appReleaseMode(Main.APP_RELEASE_MODE);
        
        this.noticeHandler = new NoticeHandler(this.textArea);
        
        upoFileChooser.setFileFilter(new FileFilterUpo());
        xadesFileChooser.setFileFilter(new FileFilterXades());
        
        LOGGER.log(Level.FINE, "{0} swing application launched!", Main.APP_NAME);
    }

    private void initAppContext()
    {
        Main.init();
    }
    
    private void manageVisibility(ActionEvent evt)
    {
        if (evt != null)
        {
            if (evt.getSource() == checkStatusMenuItem)
            {
                this.checkStatusMenuItemVisibility(!checkStatusMenuItem.isEnabled());
            }
            else if (evt.getSource() == openFileMenuItem)
            {
                this.openFileMenuItemVisibility(!openFileMenuItem.isEnabled());
            }
            else if (evt.getSource() == closeFileMenuItem)
            {
                this.closeFileMenuItemVisibility(!closeFileMenuItem.isEnabled());
            }
        }
    }
    
    private synchronized void checkStatusMenuItemVisibility(boolean visibility)
    {
        checkStatusMenuItem.setEnabled(visibility);
        openFileMenuItem.setEnabled(visibility);
        
        if (Main.APP_RELEASE_LEVEL != Main.ReleaseLevel.TST)
        {
            modeToggleButton.setEnabled(visibility);
        }
    }
    
    private void openFileMenuItemVisibility(boolean visibility)
    {
        sendFileMenuItem.setEnabled(!visibility);
        openFileMenuItem.setEnabled(visibility);
        closeFileMenuItem.setEnabled(!visibility);
        checkStatusMenuItem.setEnabled(visibility);
    }
    
    private void closeFileMenuItemVisibility(boolean visibility)
    {
        openFileMenuItem.setEnabled(!visibility);
        sendFileMenuItem.setEnabled(visibility);
        closeFileMenuItem.setEnabled(visibility);
        statusFileMenuItem.setEnabled(visibility);
        checkStatusMenuItem.setEnabled(!visibility);
        
        if (Main.APP_RELEASE_LEVEL != Main.ReleaseLevel.TST)
        {
            modeToggleButton.setEnabled(!visibility);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        upoFileChooser = new javax.swing.JFileChooser();
        xadesFileChooser = new javax.swing.JFileChooser();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        statusPanel = new javax.swing.JPanel();
        modeToggleButton = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openFileMenuItem = new javax.swing.JMenuItem();
        sendFileMenuItem = new javax.swing.JMenuItem();
        statusFileMenuItem = new javax.swing.JMenuItem();
        closeFileMenuItem = new javax.swing.JMenuItem();
        exitSeparator = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        statusMenu = new javax.swing.JMenu();
        checkStatusMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Main.APP_NAME + " " + Main.APP_VERSION + " - " + Main.APP_TITLE);
        setName("appFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
        });

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        textArea.setEditable(false);
        textArea.setBackground(java.awt.Color.lightGray);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setTabSize(4);
        textArea.setWrapStyleWord(true);
        scrollPane.setViewportView(textArea);

        modeToggleButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        modeToggleButton.setText(JPK_SEND_MODE_TST);
        modeToggleButton.setPreferredSize(new java.awt.Dimension(130, 25));
        modeToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modeToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(modeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(modeToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setPreferredSize(new java.awt.Dimension(70, 20));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Plik");

        openFileMenuItem.setMnemonic('o');
        openFileMenuItem.setText("Otwórz");
        openFileMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openFileMenuItem);

        sendFileMenuItem.setText("Wyślij");
        sendFileMenuItem.setEnabled(false);
        sendFileMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sendFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(sendFileMenuItem);

        statusFileMenuItem.setText("Status");
        statusFileMenuItem.setEnabled(false);
        statusFileMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                statusFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(statusFileMenuItem);

        closeFileMenuItem.setText("Zamknij");
        closeFileMenuItem.setEnabled(false);
        closeFileMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(closeFileMenuItem);
        fileMenu.add(exitSeparator);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Wyjście");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        statusMenu.setText("Status");

        checkStatusMenuItem.setText("Sprawdź");
        checkStatusMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkStatusMenuItemActionPerformed(evt);
            }
        });
        statusMenu.add(checkStatusMenuItem);

        menuBar.add(statusMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 357, Short.MAX_VALUE)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addGap(25, 25, 25)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        
        Main.closeHandlers();
        
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileMenuItemActionPerformed

        xadesFile = null;
        
        textArea.setText(null);
        
        xadesFileChooser.setSelectedFile(null);
        
        switch (xadesFileChooser.showOpenDialog(this))
        {
            case JFileChooser.APPROVE_OPTION:

                xadesFile = xadesFileChooser.getSelectedFile();

                break;
        }

        if ((xadesFile != null) && (xadesFile.isFile()))
        {
            try
            {
                int dotIndex;

                if ((dotIndex = xadesFile.getAbsolutePath().lastIndexOf(".")) != -1)
                {
                    Main.fileHandler = new FileHandler(xadesFile.getAbsolutePath().substring(0, dotIndex) + ".log", true);
                }
                else
                {
                    Main.fileHandler = new FileHandler(xadesFile.getAbsolutePath() + ".log", true);
                }

                Main.fileHandler.setFormatter(new SimpleFormatter());

                restClient = new RestClient(Main.APP_RELEASE_MODE, new Handler[] {Main.fileHandler, this.noticeHandler});
                
                RestClient.LOGGER.log(Level.INFO, "Wczytano plik: {0}\n", xadesFile.getAbsolutePath());
                
                this.manageVisibility(evt);
            }
            catch (IOException ex)
            {
                LOGGER.log(Level.SEVERE, ex.getMessage(), ex);
            }
        }
        else
        {
            xadesFile = null;
        }
    }//GEN-LAST:event_openFileMenuItemActionPerformed

    private void closeFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFileMenuItemActionPerformed

        if (xadesFile != null)
        {
            RestClient.LOGGER.log(Level.INFO, "Zamknięto plik: {0}\n", xadesFile.getAbsolutePath());
        }
            
        if (restClient != null)
        {
            restClient.cleanup();
        }
        
        xadesFile = null;
        restClient = null;
        textArea.setText(null);
        
        this.manageVisibility(evt);
    }//GEN-LAST:event_closeFileMenuItemActionPerformed

    private void sendFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileMenuItemActionPerformed

        if ((xadesFile != null) && (restClient != null))
        {
            boolean approve = false;
            
            if (Main.APP_RELEASE_MODE == Main.ReleaseMode.PRD)
            {
                switch (JOptionPane.showConfirmDialog(this, "Wysłać dane do usługi produkcyjnej?", JPK_SEND_MODE_PRD, JOptionPane.YES_NO_OPTION))
                {
                    case JFileChooser.APPROVE_OPTION:
                    {
                        approve = true;

                        break;
                    }
                }
            }
            else if (Main.APP_RELEASE_MODE == Main.ReleaseMode.TST)
            {
                switch (JOptionPane.showConfirmDialog(this, "Wysłać dane do usługi testowej?", JPK_SEND_MODE_TST, JOptionPane.YES_NO_OPTION))
                {
                    case JFileChooser.APPROVE_OPTION:
                    {
                        approve = true;

                        break;
                    }
                }
            }
            
            if (approve)
            {
                RestSend restSend = new RestSend(this.restClient);
                
                sendFileMenuItem.setEnabled(false);
                closeFileMenuItem.setEnabled(false);
                
                restSend.start();
            }
        }
    }//GEN-LAST:event_sendFileMenuItemActionPerformed

    private void checkStatusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStatusMenuItemActionPerformed
        
        textArea.setText(null);
        
        String referenceNumber = JOptionPane.showInputDialog(this, "Podaj numer referencyjny:", "Sprawdzenie statusu transakcji", JOptionPane.QUESTION_MESSAGE);

        RestClient statusClient = new RestClient(Main.APP_RELEASE_MODE, new Handler[] {this.noticeHandler});
        
        if ((referenceNumber != null) && ((referenceNumber = referenceNumber.trim()).length() != 0))
        {
            if (referenceNumber.matches("[a-zA-Z0-9]{32}"))
            {
                RestStatus restStatus = new RestStatus(statusClient, referenceNumber);
                
                this.manageVisibility(evt);
                
                restStatus.start();
            }
            else
            {
                RestClient.LOGGER.log(Level.INFO, "Niepoprawny format numeru referencyjnego!");
                RestClient.LOGGER.log(Level.FINE, referenceNumber);
            }
        }
        else
        {
            RestClient.LOGGER.log(Level.INFO, "Nie podano numeru referencyjnego!");
        }
    }//GEN-LAST:event_checkStatusMenuItemActionPerformed

    private void statusFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFileMenuItemActionPerformed
        
        if ((restClient != null) && (restClient.successFinish() || restClient.successStatus()))
        {
            RestStatus restStatus = new RestStatus(restClient);

            restStatus.start();
        }
    }//GEN-LAST:event_statusFileMenuItemActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Main.closeHandlers();
    }//GEN-LAST:event_formWindowClosed

    private void modeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeToggleButtonActionPerformed

        if (modeToggleButton.isSelected())
        {
            this.appReleaseMode(ReleaseMode.PRD);
        }
        else
        {
            this.appReleaseMode(ReleaseMode.TST);
        }
    }//GEN-LAST:event_modeToggleButtonActionPerformed

    private void appReleaseMode(ReleaseMode releaseMode)
    {
        textArea.setText(null);
        
        Main.APP_RELEASE_MODE = releaseMode;
        
        if (Main.APP_RELEASE_MODE == ReleaseMode.PRD)
        {
            if (!modeToggleButton.isSelected())
            {
                modeToggleButton.setSelected(true);
            }
            
            modeToggleButton.setText(JPK_SEND_MODE_PRD);
            modeToggleButton.setForeground(Color.red);
            textArea.setBackground(java.awt.Color.black);
            textArea.setForeground(java.awt.Color.yellow);        
        }
        else if (Main.APP_RELEASE_MODE == ReleaseMode.TST)
        {
            if (modeToggleButton.isSelected())
            {
                modeToggleButton.setSelected(false);
            }
            
            modeToggleButton.setText(JPK_SEND_MODE_TST);
            modeToggleButton.setForeground(Color.black);
            textArea.setBackground(java.awt.Color.lightGray);
            textArea.setForeground(java.awt.Color.black);        
        }
    }
    
    private synchronized void saveUPO(RestClient restClient)
    {
        switch (JOptionPane.showConfirmDialog(this, "Usługa sprawdzenia statusu zwróciła UPO.\nZapisać do pliku?"))
        {
            case JFileChooser.APPROVE_OPTION:
            {
                if (upoFileChooser.getSelectedFile() == null)
                {
                    if (xadesFile != null)
                    {
                        upoFileChooser.setSelectedFile(new File(xadesFile.getParent() + File.separator + restClient.getJpkDetails().replace(":", "-") + FILE_DOT_EXT_UPO));
                    }
                    else
                    {
                        upoFileChooser.setSelectedFile(new File(FileSystemView.getFileSystemView().getDefaultDirectory() + File.separator + restClient.getJpkDetails().replace(":", "-") + FILE_DOT_EXT_UPO));
                    }
                }
                
                if (upoFileChooser.getSelectedFile().isDirectory())
                {
                    upoFileChooser.setSelectedFile(new File(upoFileChooser.getSelectedFile().getAbsolutePath() + File.separator + restClient.getJpkDetails().replace(":", "-") + FILE_DOT_EXT_UPO));
                }
                else
                {
                    upoFileChooser.setSelectedFile(new File(upoFileChooser.getSelectedFile().getParent() + File.separator + restClient.getJpkDetails().replace(":", "-") + FILE_DOT_EXT_UPO));
                }    

                switch (upoFileChooser.showSaveDialog(this))
                {
                    case JFileChooser.APPROVE_OPTION:

                        upoFile = upoFileChooser.getSelectedFile();
                        
                        PrintWriter upoWriter = null;
                        
                        try
                        {
                            upoWriter = new PrintWriter(upoFile, "UTF-8");
                            
                            upoWriter.write(restClient.getJpkUpo());
                        }
                        catch (IOException ex)
                        {
                            LOGGER.log(Level.SEVERE, null, ex);
                        }
                        finally
                        {
                            if (upoWriter != null)
                            {
                                upoWriter.close();
                            }
                        }

                        break;
                }

                break;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                //if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) 
        {
            LOGGER.log(java.util.logging.Level.SEVERE, ex.getMessage(), ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem checkStatusMenuItem;
    private javax.swing.JMenuItem closeFileMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPopupMenu.Separator exitSeparator;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JToggleButton modeToggleButton;
    private javax.swing.JMenuItem openFileMenuItem;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JMenuItem sendFileMenuItem;
    private javax.swing.JMenuItem statusFileMenuItem;
    private javax.swing.JMenu statusMenu;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextArea textArea;
    private javax.swing.JFileChooser upoFileChooser;
    private javax.swing.JFileChooser xadesFileChooser;
    // End of variables declaration//GEN-END:variables

    private class FileFilterXades extends FileFilter 
    {
        @Override
        public boolean accept(File file)
        {
            return (file.isDirectory() || file.getName().endsWith(FILE_DOT_EXT_XADES));
        }

        @Override
        public String getDescription()
        {
            return "Pliki podpisane w formacie XAdES";
        }
    }
    
    private class FileFilterUpo extends FileFilter 
    {
        @Override
        public boolean accept(File file)
        {
            return (file.isDirectory() || file.getName().endsWith(FILE_DOT_EXT_UPO));
        }

        @Override
        public String getDescription()
        {
            return "Pliki UPO w formacie XML";
        }
    }
    
    private class NoticeHandler extends Handler
    {
        JTextArea textArea = null;
        
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

        private NoticeHandler()
        {
        }
        
        public NoticeHandler(JTextArea textArea)
        {
            this.textArea = textArea;
            
            this.textArea.setText(null);
        }

        @Override
        public synchronized void publish(LogRecord record)
        {
            if (this.textArea != null)
            {
                if (record.getLevel().intValue() > Level.FINE.intValue())
                {
                    if (record.getMessage() != null)
                    {
                        String message = record.getMessage();
                        
                        if (record.getParameters() != null)
                        {
                            for (int i =0; i < record.getParameters().length; i++)
                            {
                                message = message.replace("{" + i + "}", String.valueOf(record.getParameters()[i]));
                            }
                        }
                        
                        if (message.startsWith("----------"))
                        {
                            textArea.append(message + "\n");
                        }
                        else
                        {
                            textArea.append(sdf.format(new Date(record.getMillis())) + " " + message + "\n");
                        }
                    }
                }
            }
        }

        @Override
        public void flush()
        {
        }

        @Override
        public void close() throws SecurityException 
        {
        }
    }
    
    private class RestSend extends Thread
    {
        private RestClient restClient = null;
        
        public RestSend(RestClient restClient)
        {
            this.restClient = restClient;
        }
        
        @Override
        public void run()
        {
            try
            {
                if (this.restClient != null)
                {
                    this.restClient.initUpload(xadesFile);

                    if (this.restClient.successInit())
                    {
                        this.restClient.doUpload(xadesFile);

                        if (this.restClient.successUpload())
                        {
                            this.restClient.finishUpload();

                            if (this.restClient.successFinish())
                            {
                                statusFileMenuItem.setEnabled(true);

                                statusFileMenuItemActionPerformed(null);
                            }
                        }
                    }
                }
            }
            finally
            {
                closeFileMenuItem.setEnabled(true);
            }
        }
    }
    
    private class RestStatus extends Thread
    {
        private RestClient restClient = null;
        private String referenceNumber = null;
        
        public RestStatus(RestClient restClient)
        {
            this.restClient = restClient;
        }
        
        public RestStatus(RestClient restClient, String referenceNumber)
        {
            this.restClient = restClient;
            this.referenceNumber = referenceNumber;
        }
        
        @Override
        public void run()
        {
            try
            {
                if (this.restClient != null)
                {
                    if (referenceNumber != null)
                    {
                        this.restClient.checkStatus(referenceNumber);
                    }
                    else
                    {
                        this.restClient.checkStatus();
                    }

                    if (this.restClient.successUPO())
                    {
                        saveUPO(this.restClient);
                    }

                    if (this.referenceNumber != null)
                    {
                        this.restClient.cleanup();
                    }
                }
            }
            finally
            {
                if (this.referenceNumber != null)
                {
                    checkStatusMenuItemVisibility(true);
                }
            }
        }
    }
}
